# pre-commit install --hook-type commit-msg --hook-type pre-push; pre-commit autoupdate
# pre-commit run
# pre-commit run --hook-stage commit-msg --commit-msg-filename .git/COMMIT_EDITMSG
---
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.5.2
    hooks:
      - id: commitizen
        
  - repo: local
    hooks:
      - id: Swift-Lint
        name: Swift-Lint
        entry: /opt/homebrew/bin/swiftlint . --strict --quiet true
        language: script
        pass_filenames: false

  - repo: local
    hooks:
      - id: commit-message-check
        name: Commit Message Check Shouldn't contain issue
        language: pygrep
        entry: '^.*issue.*$'
        args: [--multiline]
        stages: [commit-msg]