name: Update Changelog, Create Release

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      build_number:
        required: true
        type: string
        
env:
  GITHUB_TOKEN: ${{ secrets.ORG_BOT_PAT }}

jobs:
  changelog:
    name: Update Changelog, Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ORG_BOT_PAT}}
          fetch-depth: 0
          
      - name: Pull again (workflow uses triggered commit as base)
        run: |
          git pull
 
      - name: Update CHANGELOG
        id: changelog
        uses: Requarks/changelog-action@v1.5.0
        with:
          token: ${{ secrets.ORG_BOT_PAT }}
          tag: ${{ inputs.tag_name }}
          excludeTypes: ""
          includeInvalidCommits: true
 
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag_name }}
          draft: false
          name: ${{ inputs.tag_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.ORG_BOT_PAT }}
          
      - name: Whats new
        run: |
          echo "${{ steps.changelog.outputs.changes }}"
 
      - name: Commit CHANGELOG.md
        run: |
          git config --global user.email "bot@nthstate.com"
          git config --global user.name "nthState-bot"
          git pull
          git checkout release/${{ inputs.tag_name }}
          git add "CHANGELOG.md"
          git commit -m "docs: update CHANGELOG.md for ${{ inputs.tag_name }} [skip ci]" || echo "No changes to commit"
          git push
          
      - name: Create Pull Request
        run: |
          gh pr create --base main --head release/${{ inputs.tag_name }} --title "build: release/${{ inputs.tag_name }}"
          