name: Bump Version, Create Changlog, Create Tag

on:
  workflow_dispatch:

concurrency:
  group: "${{ github.ref }}_bump"
  cancel-in-progress: false
  
env:
  GITHUB_TOKEN: ${{ secrets.ORG_BOT_PAT }}
  VERSION_FILE: "Configuration/Version.xcconfig"
  GITHUB_EMAIL: "bot@nthstate.com"
  GITHUB_USERNAME: "nthState-bot"

jobs:
  bumpchangelogtag:
    name: Bump Version, Create Changlog, Create Tag
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Find version, build number and update
        run: |
          # Find build number and increment
          CURRENT_PROJECT_VERSION=$(grep -w "CURRENT_PROJECT_VERSION" "${{ env.VERSION_FILE }}" | cut -d'=' -f2 | tr -d ' ')
          ((CURRENT_PROJECT_VERSION+=1))
          sed -i "s/\(CURRENT_PROJECT_VERSION *= *\).*/\1$CURRENT_PROJECT_VERSION/" "${{ env.VERSION_FILE }}"

          # Find version number
          MARKETING_VERSION=$(grep -w "MARKETING_VERSION" "${{ env.VERSION_FILE }}" | cut -d'=' -f2 | tr -d ' ')

          NEW_TAG="v$MARKETING_VERSION+$CURRENT_PROJECT_VERSION"
          echo $NEW_TAG

          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$CURRENT_PROJECT_VERSION" >> $GITHUB_ENV
          
          
      - name: Setup Git user
        run: |
          git config --global user.email "${{ env.GITHUB_EMAIL }}"
          git config --global user.name "${{ env.GITHUB_USERNAME }}"
          git config --global --add --bool push.autoSetupRemote true
          
      - name: Create tag
        run: |
          git config --global user.email "${{ env.GITHUB_EMAIL }}"
          git config --global user.name "${{ env.GITHUB_USERNAME }}"
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
          
      - name: Create Branch
        run: |
          git checkout -b release/${{ env.NEW_TAG }}
          
      - name: Commit build number
        run: |
          git checkout release/${{ env.NEW_TAG }}
          git add "${{ env.VERSION_FILE }}"
          git commit -m "bump: Build Number to build ${{ env.NEW_TAG }} [skip ci]" || echo "No changes to commit"
          git push 

      - name: Update CHANGELOG
        id: changelog
        uses: Requarks/changelog-action@v1.5.0
        with:
          tag: ${{ env.NEW_TAG }}               error tag not craeted here
          excludeTypes: ""
          includeInvalidCommits: true
          
      - name: Show whats new
        run: |
          echo "${{ steps.changelog.outputs.changes }}"
 
      - name: Commit CHANGELOG.md
        run: |
          git checkout release/${{ env.NEW_TAG }}
          git add "CHANGELOG.md"
          git commit -m "docs: update CHANGELOG.md for ${{ env.NEW_TAG }} [skip ci]" || echo "No changes to commit"
          git push
          
      - name: Create Pull Request
        run: |
          PR_URL=$(gh pr create --base main --head release/${{ env.NEW_TAG }} --title "build: release/${{ env.NEW_TAG }}" --body "BOT: build: release/${{ env.NEW_TAG }}")
          echo $PR_URL
          #gh pr review $PR_URL --approve
          #gh pr merge $PR_URL --squash
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          draft: false
          name: ${{ env.NEW_TAG }}
          body: ${{ steps.changelog.outputs.changes }}    
          
   