name: Lint

on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - "ios/**"

concurrency:
  group: "${{ github.ref }}_lint"
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_15_beta4.app/Contents/Developer

jobs:
  lint:
    name: SwiftLint
    runs-on: self-hosted
    timeout-minutes: 5
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run linter
        run: swiftlint --strict
 